name: Build and Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.8'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          fi

      - name: Replace image URLs for GitHub Pages
        run: |
          sed -i 's|https://gitlab.inner.advanced-tek.com.tw:8443/work-log-7ac089/images/avatar.png|https://raw.githubusercontent.com/Bgb941207/work-log/master/static/images/avatar.png|g' config.toml
          sed -i 's|https://gitlab.inner.advanced-tek.com.tw:8443/work-log-7ac089/images/github.png|https://raw.githubusercontent.com/Bgb941207/work-log/master/static/images/github.png|g' config.toml

      - name: Build Hugo site with GitHub Pages baseURL
        run: hugo --gc --minify --baseURL="https://bgb941207.github.io/work-log/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
